### ISSUE TITLE
Page Galerie

### ISSUE THREAD

**Issue by etbourreau** [etbourreau/nant-it#7]
- [x] La page galerie est accessible sous l'URI /galerie
- [x] Les items sont alignés successivement à gauche puis à droite
- [x] Les proportions sont 1/3 pour l'image et 2/3 pour le reste
- [x] Au passage de la souris, une bordure autour de la ligne en noir 1px et une couleur de fond bleutée, un curseur main et des angles arrondis comme la page de contenu

**Comment by MoonEyes** [comment]
![page galerie](https://user-images.githubusercontent.com/14891700/30522228-14e3e192-9bcd-11e7-90e5-984e06e1a4e0.jpg)
[page galerie.pdf](https://github.com/etbourreau/nant-it/files/1309166/page.galerie.pdf)
